name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Checkout scripts lib
        uses: actions/checkout@v4
        with:
          repository: serhatbasesgioglu/modulops
          ref: main
          path: modulops

      - name:
        run: dotnet build
